# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 22:47
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usaf', models.FloatField()),
                ('wban', models.FloatField()),
                ('station_na', models.CharField(max_length=254, verbose_name='Station')),
                ('ctry', models.CharField(max_length=254, verbose_name='Country')),
                ('st', models.CharField(max_length=254, verbose_name='State')),
                ('call', models.CharField(max_length=254, verbose_name='Call')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('elev', models.FloatField()),
                ('mpoint', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
