# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 22:53
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_weatherstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstation',
            name='objectid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='call',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='ctry',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='mpoint',
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='st',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='station_na',
            field=models.CharField(max_length=254),
        ),
    ]
